# Generated by Django 4.2.7 on 2025-11-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='dependente_de_execucoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='dependente_de_execucoes',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FailedPod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('namespace', models.CharField(default='default', max_length=100)),
                ('labels', models.JSONField(default=dict)),
                ('phase', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('containers', models.JSONField(default=list)),
                ('logs', models.TextField(blank=True, null=True)),
                ('nome_robo', models.CharField(blank=True, max_length=255, null=True)),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Failed Pod',
                'verbose_name_plural': 'Failed Pods',
                'db_table': 'failed_pods',
                'indexes': [models.Index(fields=['failed_at'], name='failed_pods_failed__91d8c5_idx'), models.Index(fields=['name'], name='failed_pods_name_3439a2_idx')],
            },
        ),
    ]
