# Generated by Django 5.2.9 on 2025-12-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cronjob_dependente_de_execucoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboDockerizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255, unique=True)),
                ('apelido', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('rpa', 'RPA'), ('cronjob', 'Cronjob'), ('deployment', 'Deployment')], db_index=True, max_length=20)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('docker_tag', models.CharField(max_length=100)),
                ('docker_repository', models.CharField(blank=True, max_length=255, null=True)),
                ('namespace', models.CharField(default='default', max_length=100)),
                ('qtd_max_instancias', models.IntegerField(blank=True, null=True)),
                ('qtd_ram_maxima', models.IntegerField(blank=True, null=True)),
                ('memory_limit', models.CharField(default='256Mi', max_length=20)),
                ('utiliza_arquivos_externos', models.BooleanField(default=False)),
                ('tempo_maximo_de_vida', models.IntegerField(default=600)),
                ('replicas', models.IntegerField(default=1)),
                ('ready_replicas', models.IntegerField(default=0)),
                ('available_replicas', models.IntegerField(default=0)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('suspended', models.BooleanField(default=False)),
                ('ttl_seconds_after_finished', models.IntegerField(default=60)),
                ('last_schedule_time', models.CharField(blank=True, max_length=100, null=True)),
                ('last_successful_time', models.CharField(blank=True, max_length=100, null=True)),
                ('dependente_de_execucoes', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inativado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Robô Dockerizado',
                'verbose_name_plural': 'Robôs Dockerizados',
                'db_table': 'robos_dockerizados',
            },
        ),
        migrations.DeleteModel(
            name='Cronjob',
        ),
        migrations.DeleteModel(
            name='Deployment',
        ),
        migrations.DeleteModel(
            name='RPA',
        ),
        migrations.AddIndex(
            model_name='robodockerizado',
            index=models.Index(fields=['tipo', 'ativo'], name='robos_docke_tipo_12ba07_idx'),
        ),
        migrations.AddIndex(
            model_name='robodockerizado',
            index=models.Index(fields=['nome'], name='robos_docke_nome_7533d7_idx'),
        ),
        migrations.AddIndex(
            model_name='robodockerizado',
            index=models.Index(fields=['created_at'], name='robos_docke_created_bf5d58_idx'),
        ),
    ]
