# Generated by Django 4.2.7 on 2026-01-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_robodockerizado_delete_cronjob_delete_deployment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robodockerizado',
            name='robo_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='UUID do robô no MongoDB para buscar execuções', max_length=36, null=True),
        ),
    ]
